/*****     PROMPTING DML COMMANDS     *****/


-- Updating net profit column with calculation. 


UPDATE SPOTIFY_INFO
       SET NET_PROFIT = 
                (GROSS_PROFIT + PREMIUM_GROSS_PROFIT + AD_GROSS_PROFIT - SALES_MARKETING_COST - RESEARCH_DEVELOPMENT_COST - GENERAL_ADMINSTRATIVE_COST) ;
				
SELECT *
FROM SPOTIFY_INFO;